-- SELECT*FROM ANIMAL_OUTS 
-- SELECT A.ANIMAL_ID, A.NAME 
-- FROM ANIMAL_OUTS A LEFT JOIN ANIMAL_INS B   --LIFT JOIN(on)
-- ON(A.ANIMAL_ID =B.ANIMAL_ID)
-- WHERE B.ANIMAL_ID IS NULL
-- ORDER BY A.ANIMAL_ID


-- SELECT ANIMAL_ID, O.NAME
-- FROM ANIMAL_INS I RIGHT OUTER JOIN ANIMAL_OUTS O --RIGHT JOIN (By using)
-- USING (ANIMAL_ID)   
-- WHERE I.DATETIME IS NULL
-- ORDER BY ANIMAL_ID;
SELECT B.ANIMAL_ID, B.NAME
FROM ANIMAL_INS A
RIGHT JOIN
ANIMAL_OUTS B
ON A.ANIMAL_ID=B.ANIMAL_ID
WHERE A.ANIMAL_ID IS NULL
ORDER BY B.ANIMAL_ID

-- SELECT ANIMAL_ID, NAME
-- FROM ANIMAL_OUTS
-- MINUS
-- SELECT ANIMAL_ID, NAME
-- FROM ANIMAL_INS