-- FROM 절에 SUBQUERY 줘서 다시 LEFT JOIN
SELECT NAME, DATETIME 
FROM (SELECT A.NAME, A.DATETIME 
      FROM ANIMAL_INS A LEFT JOIN ANIMAL_OUTS B
      ON A.ANIMAL_ID =B.ANIMAL_ID
      WHERE B.ANIMAL_ID IS NULL
      ORDER BY A.DATETIME)
WHERE ROWNUM <= 3;

