-- 코드를 입력하세요
SELECT A.CATEGORY, A.MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F,(SELECT CATEGORY,MAX(PRICE) MAX_PRICE FROM FOOD_PRODUCT 
                     WHERE CATEGORY IN('과자','국','김치','식용유') GROUP BY CATEGORY)A
WHERE F.CATEGORY = A.CATEGORY AND F.PRICE = A.MAX_PRICE  -- 식품 분류별 & 가격 =비싼(가격)
ORDER BY A.MAX_PRICE DESC;