SELECT PRODUCT_CODE, SUM((SALES_AMOUNT * PRICE)) SALES  //이미 합한 데이터를 조인을 통해 구해줄 수 있음
FROM PRODUCT P JOIN OFFLINE_SALE O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_CODE                  -- 상품별 묶기
ORDER BY SALES DESC, PRODUCT_CODE
