-- SELECT*FROM FOOD_ORDER;

SELECT PRODUCT_ID, PRODUCT_NAME, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM (SELECT B.PRODUCT_ID, A.PRODUCT_NAME, (A.PRICE * B.AMOUNT) AS TOTAL_SALES, B.PRODUCE_DATE
      FROM FOOD_PRODUCT A JOIN FOOD_ORDER B
      ON A.PRODUCT_ID = B.PRODUCT_ID
      WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05' 
      )
GROUP BY PRODUCT_ID,PRODUCT_NAME
ORDER BY TOTAL_SALES DESC , PRODUCT_ID;