-- <HH24 -24시간 형식 HH만쓰면 EX> 18시 =>6시>
-- TO_NUMBER() : 문자열을 숫자(정수,실수)로 변환
-- ex> 09라는 문자열을 9(정수,실수)로 변환시켜줌

SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24'))AS HOUR,  COUNT(*) AS COUNT 
FROM ANIMAL_OUTS 
GROUP BY TO_CHAR(DATETIME,'HH24')
HAVING TO_CHAR(DATETIME,'HH24') BETWEEN 9 AND 19
ORDER BY HOUR