-- 방법 1>JOIN+USING 사용 (ON 대신 =>USING 사용 , 대신 USING 절 같은경우 ALIAS를 사용하지 못함 
-- EX> USING(A.FLAVOR) =XXXX , ON쌉가능
SELECT B.INGREDIENT_TYPE AS INGREDIENT_TYPE , SUM(A.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF A JOIN ICECREAM_INFO B USING(FLAVOR)
GROUP BY INGREDIENT_TYPE




-- 방법2 2> 암묵적 조인
SELECT B.INGREDIENT_TYPE AS INGREDIENT_TYPE 
    , SUM(A.TOTAL_ORDER) AS TOTAL_ORDER
FROM     FIRST_HALF  A , ICECREAM_INFO  B -- 암묵적 JOIN
WHERE  A.FLAVOR = B.FLAVOR  -- ON ,USING 느낌
GROUP BY INGREDIENT_TYPE

